import type {
  Course,
  Placement,
  RouteSpot,
  DiscoveryRoute,
  Feedback,
  Installation,
  NightCache,
  NightEvent,
  ThirdSpace,
  UserProfile,
} from '@/types';

/**
 * Seeded Tilburg content. Used by the local provider, and mirrored by
 * supabase/seed.sql so both backends show the same city.
 *
 * Photos come from picsum.photos (deterministic per seed, no key required).
 * Swap them for municipality photography before launch.
 */

/**
 * Photography.
 *
 * Real, freely-licensed photographs from Wikimedia Commons — the actual LocHal,
 * the actual Piushaven, the actual Spoorpark water tower — rather than random
 * stock. Special:FilePath redirects to a served thumbnail at the width asked
 * for, so there is no API key and no build step.
 *
 * These are stand-ins for municipality photography, not a licence audit: check
 * the attribution requirements on each file before this ships publicly. Every
 * image renders through SafeImage/ImageCarousel, which fall back to a neutral
 * tile if a file is ever moved or deleted.
 */
/*
 * Commons serves whatever width you ask for, and the width you ask for turns
 * out to be the whole performance story on a page of cards. At 900 these
 * photos are ~360 kB each; a list page holds forty of them, which is fourteen
 * megabytes of image for cards that are never wider than about 400 px. At 480
 * the same photo is ~120 kB. Ask small here, and let heroWidth() ask for a big
 * one in the single place a big one is actually shown.
 */
const CARD_WIDTH = 480;

const commons = (file: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=${CARD_WIDTH}`;

/** Subject → a real Commons photograph of that subject. */
const PHOTOS: Record<string, string> = {
  // --- Tilburg places -------------------------------------------------------
  'loom-1': 'Spoorzone tilburg AVS 9329.jpg',
  'loom-2': 'Spoorzone Tilburg 2018 2.jpg',
  'loom-3': 'Gebouw 88.jpg',
  'harbour-1': 'De Piushaven in Tilburg in 2019.jpg',
  'harbour-2': 'De Piushaven in de zomer van 2020.jpg',
  'mural-1': '2108 Tilburg - Centrum 039- Jan Geerling.jpg',
  'mural-2': '2109 Tilburg - Centrum 136- Jan Geerling.jpg',
  'hof-1': 'Graffiti on factory wall, Locksbrook - geograph.org.uk - 1310262.jpg',
  'hof-2': 'Artist spray painting flowers (Unsplash).jpg',
  'hof-3': 'Space Invaders and spray can mosaic graffiti in Paris.jpg',
  'grove-1': 'Leijpark 1, Tilburg.jpg',
  'overhead-1': 'Tilburg Centraal Station Mosaicpanelen 2.jpg',
  'overhead-2': 'Tilburg Centraal Station Mosaicpaneel 1.jpg',

  'cachetrail-1': 'Tilburg Centraal Station Mosaicpaneel 3.jpg',
  'cachetrail-2': 'Drieburcht, renovatie Wagnerplein Tilburg 2.jpg',
  'cachetrail-3': 'Tilburg watertoren.jpg',
  'cachetrail-4': 'Spoorzone tilburg AVS 9329.jpg',
  'cachetrail-5': 'Leijpark 2, Tilburg.jpg',
  'cachetrail-6': 'Piushaven Tilburg Welkom (01).jpg',
  'cachetrail-7': '2109 Tilburg - Centrum 242- Jan Geerling.jpg',
  'cachetrail-8': 'Heuvel (Tilburg) P1050530.JPG',
  // --- Two Weeks Only: the eight spots, then the work currently in them ----
  'twoweeks-lochal': 'LocHal 20190606 - 06.jpg',
  'twoweeks-spoorpark': 'Spoorpark (Tilburg) 016.jpg',
  'twoweeks-wilhelmina': 'Wilhelminapark 63, Tilburg RM.jpg',
  'twoweeks-noordstraat': 'Willem II Straat Tilburg P1170079.jpg',
  'twoweeks-veemarkt': 'Textielmuseum Tilburg editathon 2.jpg',
  'twoweeks-koningsplein': 'Koningsplein, Tilburg 050copy.jpg',
  'twoweeks-piusplein': 'Heuvel (Tilburg) 032copy3.jpg',
  'twoweeks-hall70': 'Spoorzone Tilburg 2023.jpg',
  'twoweeks-bells': 'Bike workshop - bicycle repair shop.jpg',
  'twoweeks-windows': 'Zine Making 3.jpg',
  'twoweeks-textile': 'Tilburg textielmuseum1.jpg',
  'twoweeks-concrete': 'Buitenmuur.jpg',

  lochal: 'LocHal 20190606 - 01.jpg',
  werkplaats: 'Heuvel (Tilburg) 029copy1.jpg',
  wilhelminapark: 'Vijver Wilhelminapark (Tilburg).jpg',
  veemarkt: 'Textielmuseum Tilburg editathon 2.jpg',
  symfonie: 'Drieburcht, renovatie Wagnerplein Tilburg 1.jpg',
  kiosk: 'De Havenmeester Tilburg.jpg',

  // --- Route stops ----------------------------------------------------------
  'route1-1': 'Station Tilburg 2025 9.jpg',
  'route1-2': 'Spoorzone Tilburg 2023.jpg',
  'route1-3': 'Stadhuisplein, Tilburg P1170101.jpg',
  'route1-4': 'Piushaven Tilburg Welkom (01).jpg',
  'route1-5': 'De Piushaven in Tilburg in 2019.jpg',
  'route2-1': 'Koningsplein, Tilburg 050copy.jpg',
  'route2-2': '2108 Tilburg - Centrum 040- Jan Geerling.jpg',
  'route2-3': 'Willem II Straat Tilburg P1170079.jpg',
  'route2-4': 'Tilburg textielmuseum1.jpg',
  'route3-1': 'LocHal 20190606 - 06.jpg',
  'route3-2': 'Spoorpark (Tilburg) 016.jpg',
  'route3-3': 'Bravo bushalte wagnerplein in Tilburg.jpg',
  'route3-4': 'Buitenmuur.jpg',
  'route4-1': 'Wilhelminapark 63, Tilburg RM.jpg',
  'route4-2': 'Spoorpark (Tilburg) 018.jpg',
  'route4-3': 'Vijver Wilhelminapark (Tilburg).jpg',

  // --- Night Caches ---------------------------------------------------------
  'cache-rail': 'Spoorzone tilburg AVS 9329.jpg',
  'cache-kruik': 'Heuvel (Tilburg) P1050530.JPG',
  'cache-leij': 'Leijpark 2, Tilburg.jpg',
  'cache-courtyard': '2109 Tilburg - Centrum 242- Jan Geerling.jpg',
  'cache-tower': 'Tilburg watertoren.jpg',
  'cache-ring': 'Piushaven Tilburg Welkom (01).jpg',
  'cache-wagner': 'Drieburcht, renovatie Wagnerplein Tilburg 2.jpg',
  'cache-mirror': 'Tilburg Centraal Station Mosaicpaneel 3.jpg',

  // --- Events ---------------------------------------------------------------
  screenprint: 'Taller de serigrafía - La Ermita 1.jpg',
  nightwalk: 'Pedestrian crossing at night, Redland - geograph.org.uk - 6034970.jpg',
  artisttalk: 'LocHal 20190606 - 11.jpg',
  lateopening: 'De Havenmeester Tilburg.jpg',
  languagecafe: 'Booksa - Workshop of creative writing of short stories 55+.jpg',
  onlinemapping: 'Spoorpark (Tilburg) 006.jpg',
  zinenight: 'Zine Making 3.jpg',
  repaircafe: 'Repair Cafe by Ilvy Njiokiktjien.jpg',
  boardgames: 'Family Board Game Night-U.S. Army Garrison Humphreys, South Korea - 18 September 2014 (15098350338).jpg',
  openmic: 'Open Mic Night (62617955).jpeg',
  studycafe: 'LocHal 20190606 - 12.jpg',
  skatejam: 'Riverside Skatepark Micro Mini Ramp 20180505.jpg',
  queersocial: 'Heuvel (Tilburg) 032copy3.jpg',
  bikerepair: 'Bike workshop - bicycle repair shop.jpg',
  eetcafe: 'Heartsite Community Meal.png',
  cachewalk: 'Riverside Walk at Night - geograph.org.uk - 2749314.jpg',
  slowwalk: 'Walk in the park (50663291701).jpg',

  // --- Workshops ------------------------------------------------------------
  'course-screenprint': 'Taller de serigrafía - La Ermita 2.jpg',
  'course-darkroom': 'Photographic darkroom, probably Geoff Charles\'s darkroom, Bangor (1532108).jpg',
  'course-sound': 'NBU Sound design studio Radio and TV Center par Kossyo Hadzhigenchev-2021-b.jpg',
  'course-dye': 'Dyeing experiments with madder.jpg',
  'course-mural': 'Pop Artist Lobo in mural painting for Mercado Libre.jpg',
  'course-zine': 'Risographe .jpg',
  'course-ceramics': 'Talavera at Tlaquepaque - TaTa.jpg',
  'course-documentary': 'Street lamp in Sebnitz- Image impression of a street photographer - Image 001.jpg',
  'course-lighting': 'Programming light board.jpg',
  'course-writing': 'Chimamanda creative writing workshop.JPG',
  'course-masterclass': 'Artist painting the mural of Paulo de Carvalho, Roma Avenue, Lisbon, Portugal julesvernex2.jpg',
};

const img = (seed: string) =>
  PHOTOS[seed]
    ? commons(PHOTOS[seed])
    : // Anything not yet photographed falls back to a neutral placeholder.
      `https://picsum.photos/seed/ns-${seed}/900/506`;

/** Dates are generated relative to load so the calendar is never empty. */
function daysFromNow(days: number, hour: number, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

/** n days from now, as an ISO string. Negative goes backwards. */
function inDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export const SEED_ORGANIZER_ID = 'seed-user-organizer';
export const SEED_ADMIN_ID = 'seed-user-admin';

export const seedUsers: Array<UserProfile & { password: string }> = [
  {
    id: SEED_ORGANIZER_ID,
    email: 'organizer@nightshield.tilburg.nl',
    password: 'nightshield',
    full_name: 'Nadia el Amrani',
    pronouns: 'she/her',
    avatar_url: null,
    role: 'organizer',
    onboarding_preference: 'explorer',
    accessibility_needs: [],
    points: 95,
    created_at: daysAgo(120),
  },
  {
    id: SEED_ADMIN_ID,
    email: 'admin@nightshield.tilburg.nl',
    password: 'nightshield',
    full_name: 'Inclusivity Desk',
    pronouns: 'they/them',
    avatar_url: null,
    role: 'admin',
    onboarding_preference: 'both',
    accessibility_needs: [],
    points: 0,
    created_at: daysAgo(200),
  },
];

export const seedInstallations: Installation[] = [
  {
    id: 'inst-lochal-loom',
    is_example: true,
    title: 'The Loom Wall',
    artist: 'Sanne de Wit',
    description:
      'A ten-metre weaving painted across the old depot wall, lit from below after dusk. The pattern is taken from a 1920s Tilburg textile sample book.',
    location: { latitude: 51.5606, longitude: 5.0803 },
    address: 'Burgemeester Brokxlaan 1000, Spoorzone',
    images: [img('loom-1'), img('loom-2'), img('loom-3')],
    category: 'mural',
    is_temporary: false,
    status: 'active',
    accessibility: ['wheelchair', 'well_lit', 'step_free'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(400),
  },
  {
    id: 'inst-piushaven-lights',
    is_example: true,
    title: 'Harbour Signals',
    artist: 'Collectief Nachtlicht',
    description:
      'Twelve buoys along the quay pulse slowly in teal and pink. They brighten when someone walks past — the harbour notices you.',
    location: { latitude: 51.5495, longitude: 5.0995 },
    address: 'Piushaven kade, Tilburg',
    images: [img('harbour-1'), img('harbour-2')],
    category: 'light',
    is_temporary: true,
    status: 'active',
    accessibility: ['wheelchair', 'well_lit'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(90),
  },
  {
    id: 'inst-dwaalgebied-mural',
    is_example: true,
    title: 'Everyone Is From Somewhere',
    artist: 'Rui Ferreira & buurtgroep Dwaalgebied',
    description:
      'A portrait mural made with sixty residents of the Dwaalgebied. Each face was photographed on the street it looks onto.',
    location: { latitude: 51.558, longitude: 5.087 },
    address: 'Willem II-straat, Dwaalgebied',
    images: [img('mural-1'), img('mural-2')],
    category: 'mural',
    is_temporary: false,
    status: 'active',
    accessibility: ['wheelchair', 'step_free'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(250),
  },
  {
    id: 'inst-hall-of-fame',
    is_example: true,
    title: 'Hall of Fame — open wall',
    artist: 'Rotating',
    description:
      'A legal graffiti wall repainted almost weekly. Bring your own cans; the wall is yours between sunrise and sunset.',
    location: { latitude: 51.571, longitude: 5.068 },
    address: 'Quirijnstokstraat, Tilburg-Noord',
    images: [img('hof-1'), img('hof-2'), img('hof-3')],
    category: 'graffiti',
    is_temporary: false,
    status: 'active',
    accessibility: ['parking'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(600),
  },
  {
    id: 'inst-leijpark-sound',
    is_example: true,
    title: 'Quiet Grove',
    artist: 'Mieke Bosch',
    description:
      'A sound installation in the park: eight speakers hidden in the trees play recordings of the Leij stream as it sounded before it was culverted.',
    location: { latitude: 51.5462, longitude: 5.0929 },
    address: 'Leijpark, Tilburg',
    images: [img('grove-1')],
    category: 'sound',
    is_temporary: true,
    status: 'active',
    accessibility: ['quiet', 'wheelchair', 'pet_friendly'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(45),
  },
  {
    id: 'inst-station-ceiling',
    is_example: true,
    title: 'Overhead',
    artist: 'Studio Kuipers',
    description:
      'Mirrored panels under the station canopy that catch the platform lights. Best seen from the bicycle ramp at night.',
    location: { latitude: 51.5606, longitude: 5.0836 },
    address: 'Tilburg Centraal, Spoorlaan',
    images: [img('overhead-1'), img('overhead-2')],
    category: 'sculpture',
    is_temporary: false,
    status: 'active',
    accessibility: ['wheelchair', 'well_lit', 'step_free', 'hearing_loop'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(320),
  },
];

export const seedThirdSpaces: ThirdSpace[] = [
  {
    id: 'ts-lochal',
    is_example: true,
    name: 'LocHal Library',
    type: 'library',
    description:
      'A converted locomotive hall. Free to sit, work and read; the ground-floor café stays open late on Thursdays.',
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'Burgemeester Brokxlaan 1000',
    hours_open: 'Mon–Fri 08:00–22:00 · Sat–Sun 10:00–18:00',
    cost: 'Free',
    accessibility: ['wheelchair', 'quiet', 'step_free', 'hearing_loop', 'gender_neutral_toilets'],
    image_url: img('lochal'),
    created_by: null,
    created_at: daysAgo(500),
  },
  {
    id: 'ts-hall-of-fame-cafe',
    is_example: true,
    name: 'Café de Werkplaats',
    type: 'cafe',
    description:
      'Neighbourhood café run by volunteers. Coffee is €1, nobody minds how long you stay, and there is always someone to talk to.',
    location: { latitude: 51.5688, longitude: 5.0731 },
    address: 'Wagnerplein 12, Tilburg-Noord',
    hours_open: 'Tue–Sat 10:00–23:00',
    cost: 'Under €5',
    accessibility: ['wheelchair', 'pet_friendly', 'step_free'],
    image_url: img('werkplaats'),
    created_by: null,
    created_at: daysAgo(180),
  },
  {
    id: 'ts-wilhelminapark',
    is_example: true,
    name: 'Wilhelminapark',
    type: 'park',
    description:
      'The oldest park in the city. Lit paths on the north side, benches facing the bandstand, busy until late in summer.',
    location: { latitude: 51.5643, longitude: 5.079 },
    address: 'Wilhelminapark, Tilburg',
    hours_open: 'Always open',
    cost: 'Free',
    accessibility: ['wheelchair', 'pet_friendly', 'well_lit'],
    image_url: img('wilhelminapark'),
    created_by: null,
    created_at: daysAgo(700),
  },
  {
    id: 'ts-veemarkt-studio',
    is_example: true,
    /*
     * Invented, like everything seeded here. It used to sit at Veemarktstraat
     * 44, which is 013 Poppodium — a real venue with a real front door. An
     * Example flag covers "this listing is made up"; it does not cover putting
     * a made-up business at a real one's address, which is the kind of detail
     * somebody local notices immediately.
     */
    name: 'Veemarkt Studios',
    type: 'studio',
    description:
      'Shared maker space in the Veemarktkwartier. Drop-in evenings on Wednesdays — sewing machines, a laser cutter and a very loud kettle.',
    location: { latitude: 51.559, longitude: 5.0895 },
    address: 'Veemarktstraat 62',
    hours_open: 'Wed 18:00–22:00 drop-in · otherwise by arrangement',
    cost: '€5 per evening',
    accessibility: ['wheelchair', 'step_free'],
    image_url: img('veemarkt'),
    created_by: null,
    created_at: daysAgo(150),
  },
  {
    id: 'ts-buurthuis-reeshof',
    is_example: true,
    name: 'Buurthuis De Symfonie',
    type: 'community_centre',
    description:
      'Community centre with a warm room in winter, language café on Tuesdays and a games night that welcomes newcomers.',
    location: { latitude: 51.5622, longitude: 5.0069 },
    address: 'Eilenbergstraat 250, Reeshof',
    hours_open: 'Mon–Fri 09:00–21:00',
    cost: 'Free',
    accessibility: ['wheelchair', 'quiet', 'hearing_loop', 'service_animal', 'step_free'],
    image_url: img('symfonie'),
    created_by: null,
    created_at: daysAgo(300),
  },
  {
    id: 'ts-piushaven-kiosk',
    is_example: true,
    name: 'Kiosk Piushaven',
    type: 'cafe',
    description:
      'Waterside kiosk with outdoor heaters. Stays open while the harbour lights are on, which is most of the year.',
    location: { latitude: 51.5503, longitude: 5.0978 },
    address: 'Piushaven 1',
    hours_open: 'Daily 11:00–00:00',
    cost: 'Under €10',
    accessibility: ['wheelchair', 'well_lit', 'pet_friendly'],
    image_url: img('kiosk'),
    created_by: null,
    created_at: daysAgo(210),
  },
];

export const seedRoutes: DiscoveryRoute[] = [
  {
    id: 'route-lit-way-home',
    is_example: true,
    title: 'The Lit Way Home',
    description:
      'Station to Piushaven along streets that stay lit and busy after midnight. Built from three years of resident reports.',
    type: 'safe',
    distance_km: 2.6,
    estimated_time_minutes: 32,
    start_location: { latitude: 51.5606, longitude: 5.0836 },
    end_location: { latitude: 51.5503, longitude: 5.0978 },
    stops: [
      {
        order: 1,
        title: 'Tilburg Centraal — south exit',
        note: 'Start at the taxi rank. Staff on the platform until 01:00.',
        image_url: img('route1-1'),
        location: { latitude: 51.5606, longitude: 5.0836 },
      },
      {
        order: 2,
        title: 'Spoorlaan',
        note: 'Wide pavement, continuous lighting, night bus stop halfway.',
        image_url: img('route1-2'),
        location: { latitude: 51.5598, longitude: 5.0868 },
      },
      {
        order: 3,
        title: 'Stadhuisplein',
        note: 'Open square, people around until late. Public toilets on the east side.',
        image_url: img('route1-3'),
        location: { latitude: 51.5595, longitude: 5.089 },
      },
      {
        order: 4,
        title: 'Piushavenlaan',
        note: 'Quieter, but the harbour lights start here and the kiosk is open.',
        image_url: img('route1-4'),
        location: { latitude: 51.5545, longitude: 5.0942 },
      },
      {
        order: 5,
        title: 'Piushaven kade',
        note: 'You have arrived. Benches, water, and the Harbour Signals installation.',
        image_url: img('route1-5'),
        location: { latitude: 51.5503, longitude: 5.0978 },
      },
    ],
    accessibility: ['wheelchair', 'well_lit', 'step_free'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(160),
  },
  {
    id: 'route-dwaalgebied-art',
    is_example: true,
    title: 'Dwaalgebied Art Walk',
    description:
      'An hour through the wandering quarter: murals, galleries with lit windows, and two courtyards most people walk straight past.',
    type: 'art_walk',
    distance_km: 1.5,
    estimated_time_minutes: 55,
    start_location: { latitude: 51.5565, longitude: 5.077 },
    end_location: { latitude: 51.559, longitude: 5.0895 },
    stops: [
      {
        order: 1,
        title: 'Koningsplein',
        note: 'Meet at the fountain. Pick up a paper map from the kiosk if you want one.',
        image_url: img('route2-1'),
        location: { latitude: 51.5565, longitude: 5.077 },
      },
      {
        order: 2,
        title: 'Everyone Is From Somewhere',
        note: 'Sixty neighbours, one wall. Look for your own street in the background.',
        image_url: img('route2-2'),
        location: { latitude: 51.558, longitude: 5.087 },
      },
      {
        order: 3,
        title: 'Willem II-straat galleries',
        note: 'Six ground-floor studios. Lights stay on until 23:00 even when closed.',
        image_url: img('route2-3'),
        location: { latitude: 51.559, longitude: 5.088 },
      },
      {
        order: 4,
        title: 'Veemarktkwartier courtyard',
        note: 'Through the archway. Studios, a bar, and usually someone rehearsing.',
        image_url: img('route2-4'),
        location: { latitude: 51.559, longitude: 5.0895 },
      },
    ],
    accessibility: ['wheelchair', 'step_free'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(120),
  },
  {
    id: 'route-north-discovery',
    is_example: true,
    title: 'North of the Tracks',
    description:
      'For people who like not knowing what is next. Crosses into Tilburg-Noord, ends at the open graffiti wall.',
    type: 'exploration',
    distance_km: 2.2,
    estimated_time_minutes: 70,
    start_location: { latitude: 51.5609, longitude: 5.0797 },
    end_location: { latitude: 51.571, longitude: 5.068 },
    stops: [
      {
        order: 1,
        title: 'LocHal',
        note: 'Start warm. Grab a coffee, then out the north doors.',
        image_url: img('route3-1'),
        location: { latitude: 51.5609, longitude: 5.0797 },
      },
      {
        order: 2,
        title: 'Spoorpark',
        note: 'Cut across the lawn. The water tower is the landmark to aim for.',
        image_url: img('route3-2'),
        location: { latitude: 51.5652, longitude: 5.0742 },
      },
      {
        order: 3,
        title: 'Wagnerplein',
        note: 'Market square. Café de Werkplaats is on the corner if you need a break.',
        image_url: img('route3-3'),
        location: { latitude: 51.5688, longitude: 5.0731 },
      },
      {
        order: 4,
        title: 'Hall of Fame',
        note: 'The wall changes every week. Photograph it — it will not look like this again.',
        image_url: img('route3-4'),
        location: { latitude: 51.571, longitude: 5.068 },
      },
    ],
    accessibility: ['pet_friendly'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(80),
  },
  {
    id: 'route-quiet-green',
    is_example: true,
    title: 'The Quiet Green',
    description:
      'A low-stimulation loop through two parks. Step-free the whole way, benches every 200 metres, no through traffic.',
    type: 'safe',
    distance_km: 1.2,
    estimated_time_minutes: 40,
    start_location: { latitude: 51.5643, longitude: 5.079 },
    end_location: { latitude: 51.5643, longitude: 5.079 },
    stops: [
      {
        order: 1,
        title: 'Wilhelminapark bandstand',
        note: 'Benches face away from the road. Good place to wait for someone.',
        image_url: img('route4-1'),
        location: { latitude: 51.5643, longitude: 5.079 },
      },
      {
        order: 2,
        title: 'Spoorpark lake',
        note: 'Flat path all the way round. Toilets by the pavilion.',
        image_url: img('route4-2'),
        location: { latitude: 51.5652, longitude: 5.0742 },
      },
      {
        order: 3,
        title: 'Back through the rose garden',
        note: 'Quietest stretch of the loop, lit but not bright.',
        image_url: img('route4-3'),
        location: { latitude: 51.5648, longitude: 5.0776 },
      },
    ],
    accessibility: ['wheelchair', 'quiet', 'step_free', 'pet_friendly'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(60),
  },
  {
    id: 'route-two-weeks-only',
    is_example: true,
    rotates: true,
    title: 'Two Weeks Only',
    description:
      'A loop with eight empty spots on it. Anyone can put a small piece of work in one, and it stays for a fortnight — then the maker takes it home and someone else fills the gap. Walk it every couple of weeks and it is never the same route twice.',
    type: 'art_walk',
    distance_km: 5.9,
    estimated_time_minutes: 80,
    start_location: { latitude: 51.5607, longitude: 5.0799 },
    end_location: { latitude: 51.5617, longitude: 5.083 },
    stops: [
      {
        order: 1,
        title: 'LocHal forecourt',
        note: 'Spot 1 is on the low wall by the bicycle racks. Start here.',
        image_url: img('twoweeks-lochal'),
        location: { latitude: 51.5607, longitude: 5.0799 },
      },
      {
        order: 2,
        title: 'Wilhelminapark bandstand',
        note: 'Spot 2 is on the bandstand step, under cover when it rains.',
        image_url: img('twoweeks-wilhelmina'),
        location: { latitude: 51.5645, longitude: 5.074 },
      },
      {
        order: 3,
        title: 'Noordstraat underpass',
        note: 'Spot 3 is the ledge halfway through. Bright, and never quiet.',
        image_url: img('twoweeks-noordstraat'),
        location: { latitude: 51.562, longitude: 5.0865 },
      },
      {
        order: 4,
        title: 'Veemarktstraat, Dwaalgebied',
        note: 'Spot 4 is the shelf beside the studio door.',
        image_url: img('twoweeks-veemarkt'),
        location: { latitude: 51.559, longitude: 5.0895 },
      },
      {
        order: 5,
        title: 'Piusplein',
        note: 'Spot 5 is the window sill of the old kiosk. Busy until late.',
        image_url: img('twoweeks-piusplein'),
        location: { latitude: 51.5548, longitude: 5.09 },
      },
      {
        order: 6,
        title: 'Koningsplein',
        note: 'Spot 6 is on the planter edge, facing the square.',
        image_url: img('twoweeks-koningsplein'),
        location: { latitude: 51.557, longitude: 5.0855 },
      },
      {
        order: 7,
        title: 'Spoorpark, Ringbaan gate',
        note: 'Spot 7 sits on the gatepost. Park is open and lit until midnight.',
        image_url: img('twoweeks-spoorpark'),
        location: { latitude: 51.5556, longitude: 5.074 },
      },
      {
        order: 8,
        title: 'Spoorzone, Hall 70 wall',
        note: 'Spot 8 is the last one, on the brick ledge. Back to the LocHal in five minutes.',
        image_url: img('twoweeks-hall70'),
        location: { latitude: 51.5617, longitude: 5.083 },
      },
    ],
    accessibility: ['wheelchair', 'step_free', 'well_lit'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(45),
  },
  {
    id: 'route-night-cache-trail',
    is_example: true,
    title: 'The Night Cache trail',
    description:
      'All eight Night Caches in one walk, ordered so you never double back. It is the longest route in the app by a distance and it crosses the whole city, so treat it as an afternoon and an evening rather than an hour. The caches are worth points on their own; finishing the trail is worth the usual route reward on top.',
    type: 'art_walk',
    distance_km: 8.1,
    estimated_time_minutes: 165,
    start_location: { latitude: 51.5608, longitude: 5.0838 },
    end_location: { latitude: 51.5588, longitude: 5.0902 },
    stops: [
      {
        order: 1,
        title: 'Tilburg Centraal — Find Yourself Overhead',
        note: 'Cache 1 is in the station hall. Look up at the mosaic, then down at your own reflection.',
        image_url: img('cachetrail-1'),
        location: { latitude: 51.5608, longitude: 5.0838 },
      },
      {
        order: 2,
        title: 'Tilburg-Noord — The Corner That Waited',
        note: 'Cache 2. The furthest north, and the quietest. Bus 5 runs back if you need it.',
        image_url: img('cachetrail-2'),
        location: { latitude: 51.5686, longitude: 5.0734 },
      },
      {
        order: 3,
        title: 'Spoorpark — The Water Tower Bolt',
        note: 'Cache 3, at the foot of the tower. Park gates close at midnight.',
        image_url: img('cachetrail-3'),
        location: { latitude: 51.5654, longitude: 5.0744 },
      },
      {
        order: 4,
        title: 'Spoorzone — The Last Rail',
        note: 'Cache 4, outside the LocHal. One rail was left in the pavement on purpose.',
        image_url: img('cachetrail-4'),
        location: { latitude: 51.5607, longitude: 5.0799 },
      },
      {
        order: 5,
        title: 'Leijpark — The Drowned Stream',
        note: 'Cache 5. The longest leg of the trail, and the darkest. Go before dusk or go with someone.',
        image_url: img('cachetrail-5'),
        location: { latitude: 51.5465, longitude: 5.0933 },
      },
      {
        order: 6,
        title: 'Piushaven — Ring Number Four',
        note: 'Cache 6, on the quay. Kiosk open late, benches, and the harbour lights.',
        image_url: img('cachetrail-6'),
        location: { latitude: 51.5499, longitude: 5.0989 },
      },
      {
        order: 7,
        title: 'Dwaalgebied — Sixty Windows',
        note: 'Cache 7. Back into the wandering quarter, where the galleries stay lit.',
        image_url: img('cachetrail-7'),
        location: { latitude: 51.5582, longitude: 5.0873 },
      },
      {
        order: 8,
        title: 'Heuvel — The Man With The Jug',
        note: 'Cache 8, at the statue. The end of the trail, and the busiest square on it.',
        image_url: img('cachetrail-8'),
        location: { latitude: 51.5588, longitude: 5.0902 },
      },
    ],
    /*
     * Not well_lit. The trail is 8.1 km across the whole city and its own stop
     * note for the Leijpark leg says "the longest leg of the trail, and the
     * darkest. Go before dusk or go with someone." A lighting tag is a safety
     * claim in an app whose whole subject is walking at night, so it does not
     * get to contradict the directions underneath it.
     */
    accessibility: ['step_free'],
    created_by: null,
    moderation_status: 'approved',
    created_at: daysAgo(30),
  },
];

/*
 * Events are free, or as close to it as materials allow.
 *
 * The point of the programme is to get people through the door, and a ticket
 * price is the first thing that stops someone coming on their own. Where a
 * charge exists it covers consumables — ink, paper — and stays at a few euro.
 * Anything that needs real money is a Workshop, and those are bought with
 * points rather than cash.
 */
export const seedEvents: NightEvent[] = [
  {
    id: 'evt-screenprint',
    is_example: true,
    attendance_code: 'SCREEN25',
    title: 'Screenprint your own patch',
    description:
      'Print your own patch and take it home the same evening. You get the ink, the screen and someone to show you each step. Bring a jacket or a bag to print on, or use one of ours. No experience needed.',
    category: 'workshop',
    location: { latitude: 51.559, longitude: 5.0895 },
    address: 'Veemarktstraat 62',
    start_time: daysFromNow(2, 19),
    end_time: daysFromNow(2, 21, 30),
    capacity: 16,
    cost_euros: 3,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('screenprint'),
    accessibility: ['wheelchair', 'step_free'],
    is_virtual: false,
    virtual_url: null,
    is_featured: true,
    updated_at: null,
    created_at: daysAgo(20),
  },
  {
    id: 'evt-night-walk',
    is_example: true,
    attendance_code: 'NIGHTW18',
    title: 'Night walk: The Lit Way Home',
    description:
      'We walk one of the safe routes together and talk about what makes a street feel good to walk at night: lighting, how busy it is, and what is open. About an hour, at an easy pace.',
    category: 'social',
    location: { latitude: 51.5606, longitude: 5.0836 },
    address: 'Tilburg Centraal, south exit',
    start_time: daysFromNow(4, 20, 30),
    end_time: daysFromNow(4, 22),
    capacity: 30,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('nightwalk'),
    accessibility: ['wheelchair', 'well_lit', 'step_free', 'service_animal'],
    is_virtual: false,
    virtual_url: null,
    is_featured: true,
    updated_at: null,
    created_at: daysAgo(15),
  },
  {
    id: 'evt-artist-talk',
    is_example: true,
    attendance_code: 'ARTIST25',
    title: 'Artist talk: Sanne de Wit on The Loom Wall',
    description:
      'Sanne de Wit talks about painting The Loom Wall, from the first sketch to the finished mural. Thirty minutes of talking, then questions. Free, and you do not need to know anything about art.',
    category: 'art_talk',
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'LocHal, Stadszaal',
    start_time: daysFromNow(7, 19, 30),
    end_time: daysFromNow(7, 21),
    capacity: 60,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('artisttalk'),
    accessibility: ['wheelchair', 'hearing_loop', 'step_free', 'quiet'],
    is_virtual: false,
    virtual_url: null,
    is_featured: true,
    updated_at: null,
    created_at: daysAgo(12),
  },
  {
    id: 'evt-late-opening',
    is_example: true,
    attendance_code: 'LATEOP32',
    title: 'Late opening — Kiosk Piushaven',
    description:
      'The kiosk on the harbour stays open late. Hot drinks, a place to sit by the water, and no pressure to buy anything. Come alone or bring people.',
    category: 'nightlife',
    location: { latitude: 51.5503, longitude: 5.0978 },
    address: 'Piushaven 1',
    start_time: daysFromNow(5, 22),
    end_time: daysFromNow(6, 2),
    capacity: 150,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('lateopening'),
    accessibility: ['wheelchair', 'well_lit'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(9),
  },
  {
    id: 'evt-language-cafe',
    is_example: true,
    attendance_code: 'LANGUA39',
    title: 'Language café',
    description:
      'Practise Dutch or English with people who are also learning. You sit at a table, someone starts a topic, and you talk. All levels are welcome, including complete beginners.',
    category: 'social',
    location: { latitude: 51.5622, longitude: 5.0069 },
    address: 'Buurthuis De Symfonie, Reeshof',
    start_time: daysFromNow(1, 19),
    end_time: daysFromNow(1, 21),
    capacity: 40,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('languagecafe'),
    accessibility: ['wheelchair', 'quiet', 'hearing_loop', 'service_animal'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(30),
  },
  {
    id: 'evt-online-mapping',
    is_example: true,
    attendance_code: 'ONLINE46',
    title: 'Online: map your own safe route',
    description:
      'An online session where we build a safe route together on the map. You need a laptop and about an hour. We send the link to everyone who says they are coming.',
    category: 'workshop',
    location: null,
    address: null,
    start_time: daysFromNow(9, 18),
    end_time: daysFromNow(9, 19),
    capacity: 25,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('onlinemapping'),
    accessibility: ['hearing_loop', 'quiet'],
    is_virtual: true,
    virtual_url: 'https://meet.example.org/night-shield-mapping',
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(6),
  },
  // ---- Free things, every week ---------------------------------------------
  // Cost is the quietest barrier there is. Everything below is €0, recurring,
  // and needs no sign-up — the section of the calendar that has to stay full.
  {
    id: 'evt-repair-cafe',
    is_example: true,
    attendance_code: 'REPAIR25',
    title: 'Repair Café',
    description:
      'Bring something broken and repair it with help: a lamp, a kettle, a jacket, a bag. Volunteers have the tools and show you how, rather than doing it for you. Free.',
    category: 'workshop',
    location: { latitude: 51.5622, longitude: 5.0069 },
    address: 'Buurthuis De Symfonie, Eilenbergstraat 250',
    start_time: daysFromNow(3, 14),
    end_time: daysFromNow(3, 17),
    capacity: null,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Buurthuis De Symfonie',
    image_url: img('repaircafe'),
    accessibility: ['wheelchair', 'step_free', 'hearing_loop', 'service_animal'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(50),
  },
  {
    id: 'evt-board-games',
    is_example: true,
    attendance_code: 'BOARDG25',
    title: 'Board game night',
    description:
      'Board games in the warm, with people who will explain the rules. There are short games for a first visit and longer ones if you stay. Come on your own — most people do.',
    category: 'social',
    location: { latitude: 51.5688, longitude: 5.0731 },
    address: 'Café de Werkplaats, Wagnerplein 12',
    start_time: daysFromNow(2, 19, 30),
    end_time: daysFromNow(2, 23),
    capacity: null,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Café de Werkplaats',
    image_url: img('boardgames'),
    accessibility: ['wheelchair', 'step_free', 'quiet', 'pet_friendly'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(48),
  },
  {
    id: 'evt-open-mic',
    is_example: true,
    attendance_code: 'OPENMI94',
    title: 'Open mic — first-timers only',
    description:
      'An open mic for people who have never done one. Five minutes each: music, poems, jokes, anything. The audience is on your side. You can also just come and listen.',
    category: 'art_talk',
    location: { latitude: 51.559, longitude: 5.0895 },
    address: 'Veemarkt Studios, Veemarktstraat 62',
    start_time: daysFromNow(6, 20),
    end_time: daysFromNow(6, 22, 30),
    capacity: 60,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Veemarkt Studios',
    image_url: img('openmic'),
    accessibility: ['wheelchair', 'step_free', 'hearing_loop'],
    is_virtual: false,
    virtual_url: null,
    is_featured: true,
    updated_at: null,
    created_at: daysAgo(25),
  },
  {
    id: 'evt-study-cafe',
    is_example: true,
    attendance_code: 'STUDYC18',
    title: 'Study café — free coffee until closing',
    description:
      'A quiet place to study, with free coffee until closing. Big tables, plug sockets, and nobody asking you to order more. Come for an hour or stay all evening.',
    category: 'social',
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'LocHal, Kennismakerij',
    start_time: daysFromNow(1, 17),
    end_time: daysFromNow(1, 22),
    capacity: null,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'LocHal',
    image_url: img('studycafe'),
    accessibility: ['wheelchair', 'quiet', 'step_free', 'hearing_loop', 'gender_neutral_toilets'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(44),
  },
  {
    id: 'evt-skate-jam',
    is_example: true,
    attendance_code: 'SKATEJ11',
    title: 'Skate jam & paint session',
    description:
      'Skating and spray painting in the same afternoon. Boards to borrow if you do not have one, and a wall you are allowed to paint. All levels, including day one.',
    category: 'social',
    location: { latitude: 51.571, longitude: 5.068 },
    address: 'Hall of Fame, Quirijnstokstraat',
    start_time: daysFromNow(5, 14),
    end_time: daysFromNow(5, 18),
    capacity: null,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Hall of Fame collective',
    image_url: img('skatejam'),
    accessibility: ['parking', 'pet_friendly'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(22),
  },
  {
    id: 'evt-queer-social',
    is_example: true,
    attendance_code: 'QUEERS32',
    title: 'Queer social — chairs, not a dance floor',
    description:
      'A quiet social evening for LGBTQ+ people and friends. Chairs, tables and conversation — no dance floor and no loud music. Easy to join if you are new to the city.',
    category: 'social',
    location: { latitude: 51.559, longitude: 5.0895 },
    address: 'Veemarktkwartier, courtyard studio',
    start_time: daysFromNow(4, 19),
    end_time: daysFromNow(4, 22),
    capacity: 45,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Inclusivity Department',
    image_url: img('queersocial'),
    accessibility: ['wheelchair', 'quiet', 'step_free', 'gender_neutral_toilets', 'service_animal'],
    is_virtual: false,
    virtual_url: null,
    is_featured: true,
    updated_at: null,
    created_at: daysAgo(18),
  },
  {
    id: 'evt-bike-drop-in',
    is_example: true,
    attendance_code: 'BIKEDR32',
    title: 'Bike repair drop-in',
    description:
      'Bring your bike and fix it yourself, with help. Volunteers show you how to repair brakes, lights, punctures and a chain that keeps slipping. All tools are there, and you do not need any experience. Free bike lights while they last, because it gets dark early here in autumn.',
    category: 'workshop',
    location: { latitude: 51.5688, longitude: 5.0731 },
    address: 'Wagnerplein, outside the community centre',
    start_time: daysFromNow(8, 15),
    end_time: daysFromNow(8, 18),
    capacity: null,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Fietsmaatjes Noord',
    image_url: img('bikerepair'),
    accessibility: ['wheelchair', 'step_free', 'parking'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(16),
  },
  {
    id: 'evt-community-meal',
    is_example: true,
    attendance_code: 'COMMUN46',
    title: 'Community meal — pay what you can',
    description:
      'A hot meal cooked by neighbours. Pay what you can, including nothing. Sit at the long table and eat with whoever is there.',
    category: 'social',
    location: { latitude: 51.5622, longitude: 5.0069 },
    address: 'Buurthuis De Symfonie, Reeshof',
    start_time: daysFromNow(10, 18),
    end_time: daysFromNow(10, 20, 30),
    capacity: 40,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Buurthuis De Symfonie',
    image_url: img('eetcafe'),
    accessibility: ['wheelchair', 'step_free', 'hearing_loop', 'service_animal', 'quiet'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(14),
  },
  {
    id: 'evt-cache-walk',
    is_example: true,
    attendance_code: 'CACHEW18',
    title: 'Night Cache walk: the first four',
    description:
      'We walk to the first four Night Caches together and find them as a group. Good if you want to try the game once before doing it on your own. About ninety minutes.',
    category: 'social',
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'LocHal, main entrance',
    start_time: daysFromNow(11, 19, 30),
    end_time: daysFromNow(11, 22),
    capacity: 25,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('cachewalk'),
    accessibility: ['wheelchair', 'step_free', 'well_lit', 'service_animal'],
    is_virtual: false,
    virtual_url: null,
    is_featured: true,
    updated_at: null,
    created_at: daysAgo(9),
  },
  {
    id: 'evt-morning-park-run',
    is_example: true,
    attendance_code: 'MORNIN60',
    title: 'Slow walk in the Spoorpark',
    description:
      'A slow walk around the lake in the Spoorpark, at the pace of the slowest person. Forty-five minutes, then coffee at the pavilion. This is a walk, not a run.',
    category: 'social',
    location: { latitude: 51.5652, longitude: 5.0742 },
    address: 'Spoorpark pavilion',
    start_time: daysFromNow(3, 9),
    end_time: daysFromNow(3, 10, 30),
    capacity: null,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Spoorpark vrijwilligers',
    image_url: img('slowwalk'),
    accessibility: ['wheelchair', 'step_free', 'pet_friendly', 'quiet'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(12),
  },
  {
    id: 'evt-past-zine',
    is_example: true,
    attendance_code: 'PASTZI11',
    title: 'Zine night: writing the city',
    description:
      'Make a small magazine about your street in one evening. Paper, pens and a copier are provided. You leave with something you made and a copy for the library.',
    category: 'workshop',
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'LocHal, Kennismakerij',
    start_time: daysFromNow(-6, 19),
    end_time: daysFromNow(-6, 22),
    capacity: 20,
    cost_euros: 3,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('zinenight'),
    accessibility: ['wheelchair', 'quiet', 'step_free'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(40),
  },
  {
    id: 'evt-past-night-walk',
    is_example: true,
    attendance_code: 'LITWAY42',
    title: 'Night walk: the long way round',
    description:
      'A slow loop from the station to the harbour and back along the water. Twenty-two people came, which is the most so far.',
    category: 'social',
    location: { latitude: 51.5606, longitude: 5.0836 },
    address: 'Tilburg Centraal, south exit',
    start_time: daysFromNow(-6, 20, 30),
    end_time: daysFromNow(-6, 22, 0),
    capacity: 30,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Nadia el Amrani',
    image_url: img('nightwalk'),
    accessibility: ['wheelchair', 'step_free', 'well_lit'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(30),
  },
  {
    id: 'evt-past-repair-cafe',
    is_example: true,
    attendance_code: 'REPAIR17',
    title: 'Repair Café — bring something broken',
    description:
      'Lamps, kettles and one accordion. Volunteers brought tools and showed people how to repair their own things instead of doing it for them.',
    category: 'workshop',
    location: { latitude: 51.5648, longitude: 5.0776 },
    address: 'Buurthuis De Symfonie',
    start_time: daysFromNow(-3, 14, 0),
    end_time: daysFromNow(-3, 17, 0),
    capacity: 24,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Inclusivity Department',
    image_url: img('repaircafe'),
    accessibility: ['wheelchair', 'step_free', 'quiet'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(40),
  },
  {
    id: 'evt-past-artist-talk',
    is_example: true,
    attendance_code: 'LOOM88',
    title: 'Artist talk: what the mill left behind',
    description:
      'An hour about the textile factory that once stood where the Spoorzone is now, and the artworks made from what was left behind.',
    category: 'art_talk',
    location: { latitude: 51.5607, longitude: 5.0799 },
    address: 'LocHal, Stadszaal',
    start_time: daysFromNow(-11, 19, 30),
    end_time: daysFromNow(-11, 20, 30),
    capacity: 60,
    cost_euros: 0,
    organizer_id: SEED_ORGANIZER_ID,
    organizer_name: 'Inclusivity Department',
    image_url: img('artisttalk'),
    accessibility: ['wheelchair', 'step_free', 'quiet', 'well_lit'],
    is_virtual: false,
    virtual_url: null,
    is_featured: false,
    updated_at: null,
    created_at: daysAgo(45),
  },
];

/**
 * Night Caches — small details of Tilburg most people walk past.
 *
 * Each one can be logged two ways: by standing next to it, or by answering the
 * question from the photo and hint. The second route exists so that not being
 * able to get somewhere — money, mobility, or simply not fancying that street
 * after dark — never locks anyone out of the game.
 */
export const seedCaches: NightCache[] = [
  {
    id: 'cache-last-rail',
    is_example: true,
    title: 'The last rail',
    hint: 'Outside the LocHal, look down instead of up. One strip of the old depot never got lifted, and the paving was laid around it.',
    story:
      'Everything here was rails until 2009 — this was the workshop where the national fleet came to be repaired, and 1,200 people worked in the halls you are standing between. When the Spoorzone was rebuilt the planners kept exactly one rail in place, flush with the pavement, as a full-size footnote. Stand on it and you are standing where a locomotive stood.',
    location: { latitude: 51.5607, longitude: 5.0799 },
    area: 'Spoorzone',
    difficulty: 'easy',
    points: 6,
    image_url: img('cache-rail'),
    accessibility: ['wheelchair', 'step_free', 'well_lit'],
    night_only: false,
    question: 'What is set into the pavement outside the LocHal — a rail, a millstone, or a mosaic?',
    answers: ['rail', 'a rail', 'railway', 'track', 'rails'],
    created_at: daysAgo(70),
  },
  {
    id: 'cache-kruikenzeiker',
    is_example: true,
    title: 'The man with the jug',
    hint: 'Near the Heuvel, someone is permanently relieving himself into a pot. Nobody in Tilburg finds this odd. Look for the bronze.',
    story:
      "The Kruikenzeiker is Tilburg's own self-portrait. Wool needs ammonia to fix dye, so nineteenth-century mills paid households for their urine, collected in stone jugs. An entire city's nickname comes from that arrangement, and at carnival Tilburg renames itself Kruikenstad without a hint of embarrassment. The statue is what a city looks like when it decides its least glamorous history is the part worth casting in bronze.",
    location: { latitude: 51.5588, longitude: 5.0902 },
    area: 'Heuvel',
    difficulty: 'easy',
    points: 6,
    image_url: img('cache-kruik'),
    accessibility: ['wheelchair', 'step_free', 'well_lit'],
    night_only: false,
    question: 'What is the man in the statue holding?',
    answers: ['a jug', 'jug', 'kruik', 'een kruik', 'pot', 'a pot'],
    created_at: daysAgo(70),
  },
  {
    id: 'cache-drowned-stream',
    is_example: true,
    title: 'The drowned stream',
    hint: 'In the Leijpark, find the low stone curb that runs through the grass and stops for no reason. It is not decorative.',
    story:
      'The Leij is still there — it is simply underneath you, culverted in the 1950s when a stream through a park read as untidy rather than valuable. The curb traces the old bank. The Quiet Grove installation nearby plays recordings made before the water went under, which is the closest anyone can now get to hearing this park as it was.',
    location: { latitude: 51.5465, longitude: 5.0933 },
    area: 'Leijpark',
    difficulty: 'medium',
    points: 10,
    image_url: img('cache-leij'),
    accessibility: ['wheelchair', 'quiet', 'pet_friendly'],
    night_only: false,
    question: 'What runs underneath the Leijpark — a stream, a railway tunnel, or a bunker?',
    answers: ['a stream', 'stream', 'the leij', 'leij', 'river', 'a river'],
    created_at: daysAgo(60),
  },
  {
    id: 'cache-sixty-windows',
    is_example: true,
    title: 'Sixty windows',
    hint: 'Off the Willem II-straat there is an archway most people read as private. It is not. Go through it and count the faces on the wall.',
    story:
      'The Dwaalgebied is named for wandering, and this courtyard is the reward for actually doing it. The mural was photographed street by street: every face was taken on the road it now looks out over, so the people on this wall can stand in front of their own portrait. Sixty neighbours agreed. Two more are painted from memory.',
    location: { latitude: 51.5582, longitude: 5.0873 },
    area: 'Dwaalgebied',
    difficulty: 'medium',
    points: 10,
    image_url: img('cache-courtyard'),
    accessibility: ['wheelchair', 'step_free'],
    night_only: false,
    question: 'Roughly how many residents are painted on the courtyard mural?',
    answers: ['60', 'sixty', '60 people', 'sixty people'],
    created_at: daysAgo(55),
  },
  {
    id: 'cache-water-tower-bolt',
    is_example: true,
    title: 'The water tower bolt',
    hint: 'Spoorpark, at the foot of the tower. One of the base bolts is brass and the rest are steel. Somebody replaced it on purpose.',
    story:
      'The tower fed steam locomotives until diesel made it useless, and it stood empty for forty years while the city argued about demolishing it. It survived because residents put up their own money — Spoorpark was crowdfunded by the people who live around it, which is not how parks usually happen. The brass bolt was set by the volunteers who finished the base. It is the only signature they left.',
    location: { latitude: 51.5654, longitude: 5.0744 },
    area: 'Spoorpark',
    difficulty: 'hard',
    points: 16,
    image_url: img('cache-tower'),
    accessibility: ['wheelchair', 'step_free', 'pet_friendly'],
    night_only: false,
    question: 'What metal is the odd bolt at the base of the water tower?',
    answers: ['brass', 'brons', 'messing'],
    created_at: daysAgo(45),
  },
  {
    id: 'cache-harbour-ring',
    is_example: true,
    title: 'Ring number four',
    hint: 'Walk the Piushaven quay counting mooring rings from the kiosk. The fourth one is worn smooth on one side only.',
    story:
      'A century of rope pulling in the same direction did that. This was a working harbour — peat in, textiles out — until the trade left and the water sat unused for decades. It came back as somewhere to live and sit rather than somewhere to unload, and the rings were kept. After dark the Harbour Signals buoys pick up on movement along this stretch, so walking the quay lights it as you go.',
    location: { latitude: 51.5499, longitude: 5.0989 },
    area: 'Piushaven',
    difficulty: 'medium',
    points: 10,
    image_url: img('cache-ring'),
    accessibility: ['wheelchair', 'well_lit'],
    night_only: true,
    question: 'What was historically shipped out of the Piushaven — textiles, coal, or fish?',
    answers: ['textiles', 'textile', 'wool', 'cloth', 'textiel'],
    created_at: daysAgo(40),
  },
  {
    id: 'cache-wagner-corner',
    is_example: true,
    title: 'The corner that waited',
    hint: 'Wagnerplein, Tilburg-Noord. On the café side, one shopfront has its original 1960s tiling behind the newer sign. You can see it from the pavement.',
    story:
      'Tilburg-Noord was built fast in the sixties for mill workers and, later, for the people the mills recruited from Morocco and Turkey. The square was designed as its centre and then more or less written off for thirty years. Café de Werkplaats on this corner is volunteer-run, coffee is a euro, and nobody is asked how long they intend to stay — which is the whole point of a third space and the reason this corner is on the map.',
    location: { latitude: 51.5686, longitude: 5.0734 },
    area: 'Tilburg-Noord',
    difficulty: 'easy',
    points: 6,
    image_url: img('cache-wagner'),
    accessibility: ['wheelchair', 'step_free', 'pet_friendly'],
    night_only: false,
    question: 'How much does a coffee cost at Café de Werkplaats?',
    answers: ['1', '€1', '1 euro', 'one euro', 'a euro', '1eur'],
    created_at: daysAgo(35),
  },
  {
    id: 'cache-station-mirror',
    is_example: true,
    title: 'Find yourself overhead',
    hint: 'Tilburg Centraal, on the bicycle ramp. There is exactly one spot where the mirrored panels above put your own reflection directly over your head. It is closer to the railing than you think.',
    story:
      'The canopy is a listed piece of 1960s concrete engineering that the mirrored panels were designed not to touch — every fixing is clamped, nothing is drilled. The artist wanted the platform lights doubled at night, and the reflection of anyone standing underneath thrown back at them. It works properly after dark, and barely at all at noon.',
    location: { latitude: 51.5608, longitude: 5.0838 },
    area: 'Tilburg Centraal',
    difficulty: 'hard',
    points: 16,
    image_url: img('cache-mirror'),
    accessibility: ['wheelchair', 'step_free', 'well_lit', 'hearing_loop'],
    night_only: true,
    question: 'How are the mirrored panels attached to the listed station canopy?',
    answers: ['clamped', 'clamps', 'they are clamped', 'clamped on', 'not drilled'],
    created_at: daysAgo(30),
  },
];

/**
 * Grow — artistic courses bought with points instead of money.
 *
 * Every one of these has a real market price, shown next to the points price so
 * the trade is legible. The Inclusivity Department buys the places; residents
 * earn them by taking part in the city rather than by being able to afford them.
 */

export const CHANGING_ROUTE_ID = 'route-two-weeks-only';

/*
 * The eight spots are fixed and the work in them rotates. Sizes are small on
 * purpose: everything here has to be carried in by one person, survive two
 * weeks of Dutch weather, and be carried out again.
 */
export const seedRouteSpots: RouteSpot[] = [
  {
    id: 'spot-1',
    route_id: CHANGING_ROUTE_ID,
    number: 1,
    label: 'LocHal forecourt — low wall by the bicycle racks',
    hint: 'Flat brick, waist height. Weather comes straight across, so nothing paper.',
    location: { latitude: 51.5607, longitude: 5.0799 },
    max_size_cm: 40,
    accessibility: ['wheelchair', 'step_free', 'well_lit'],
  },
  {
    id: 'spot-2',
    route_id: CHANGING_ROUTE_ID,
    number: 2,
    label: 'Wilhelminapark — bandstand step',
    hint: 'Under cover. The only spot on the route where paper survives.',
    location: { latitude: 51.5645, longitude: 5.074 },
    max_size_cm: 50,
    accessibility: ['quiet', 'step_free'],
  },
  {
    id: 'spot-3',
    route_id: CHANGING_ROUTE_ID,
    number: 3,
    label: 'Noordstraat underpass — the ledge halfway through',
    hint: 'Lit all night and never empty. Loud. Sound pieces are wasted here.',
    location: { latitude: 51.562, longitude: 5.0865 },
    max_size_cm: 35,
    accessibility: ['wheelchair', 'step_free', 'well_lit'],
  },
  {
    id: 'spot-4',
    route_id: CHANGING_ROUTE_ID,
    number: 4,
    label: 'Veemarktstraat — shelf beside the studio door',
    hint: 'Sheltered, at eye height, and the studio keeps an eye on it.',
    location: { latitude: 51.559, longitude: 5.0895 },
    max_size_cm: 40,
    accessibility: ['step_free', 'well_lit'],
  },
  {
    id: 'spot-5',
    route_id: CHANGING_ROUTE_ID,
    number: 5,
    label: 'Piusplein — window sill of the old kiosk',
    hint: 'Busy until 02:00 at weekends. Nothing fragile.',
    location: { latitude: 51.5548, longitude: 5.09 },
    max_size_cm: 30,
    accessibility: ['step_free', 'well_lit'],
  },
  {
    id: 'spot-6',
    route_id: CHANGING_ROUTE_ID,
    number: 6,
    label: 'Koningsplein — planter edge facing the square',
    hint: 'Seen by everyone crossing the square. Fix it down properly.',
    location: { latitude: 51.557, longitude: 5.0855 },
    max_size_cm: 45,
    accessibility: ['wheelchair', 'step_free', 'well_lit'],
  },
  {
    id: 'spot-7',
    route_id: CHANGING_ROUTE_ID,
    number: 7,
    label: 'Spoorpark — the Ringbaan gatepost',
    hint: 'Square post, ties or clamps work best. Gets full afternoon sun.',
    location: { latitude: 51.5556, longitude: 5.074 },
    max_size_cm: 30,
    accessibility: ['step_free', 'well_lit'],
  },
  {
    id: 'spot-8',
    route_id: CHANGING_ROUTE_ID,
    number: 8,
    label: 'Spoorzone — brick ledge under the Hall 70 wall',
    hint: 'Deep ledge, sheltered from the west. The biggest spot on the route.',
    location: { latitude: 51.5617, longitude: 5.083 },
    max_size_cm: 60,
    accessibility: ['wheelchair', 'step_free'],
  },
];

/*
 * Seeded so the route shows every state at once: something fresh, something
 * nearly due, something overdue that the municipality will clear, and one
 * already taken home.
 */
export const seedPlacements: Placement[] = [
  {
    id: 'place-1',
    is_example: true,
    spot_id: 'spot-1',
    user_id: 'seed-attendee-a',
    maker_name: 'Ilse',
    title: 'Fifty bicycle bells',
    description:
      'Bells from the bike graveyard behind the station, strung on wire. It plays itself when the wind comes off the tracks.',
    materials: 'Salvaged bells, galvanised wire',
    image_url: img('twoweeks-bells'),
    placed_at: daysAgo(3),
    collect_by: inDays(11),
    status: 'live',
    collected_at: null,
  },
  {
    id: 'place-2',
    is_example: true,
    spot_id: 'spot-2',
    user_id: 'seed-attendee-b',
    maker_name: 'Tomas',
    title: 'Seven small windows',
    description:
      'Seven cut-paper panels of the houses on my street, lit from behind by a solar lamp.',
    materials: 'Cut paper, perspex box, solar lamp',
    image_url: img('twoweeks-windows'),
    placed_at: daysAgo(12),
    collect_by: inDays(2),
    status: 'live',
    collected_at: null,
  },
  {
    id: 'place-3',
    is_example: true,
    spot_id: 'spot-4',
    user_id: 'seed-attendee-c',
    maker_name: 'Reem',
    title: 'What the textile mill left',
    description: 'Loom offcuts from the TextielLab, rewoven into a small hanging panel.',
    materials: 'Wool offcuts, oak frame',
    image_url: img('twoweeks-textile'),
    placed_at: daysAgo(17),
    collect_by: inDays(-3),
    status: 'live',
    collected_at: null,
  },
  {
    id: 'place-5',
    is_example: true,
    spot_id: 'spot-3',
    user_id: 'seed-attendee-e',
    maker_name: 'Nadia',
    title: 'Flowers for a grey ledge',
    description:
      'The underpass is grey and lit all night, so I painted the thing it has none of. A hand-sized panel on the ledge, not on the wall — it comes home with me in two weeks and the wall is exactly as it was.',
    materials: 'Spray paint on a 30 cm plywood panel',
    image_url: img('hof-2'),
    placed_at: daysAgo(6),
    collect_by: inDays(8),
    status: 'live',
    collected_at: null,
  },
  {
    id: 'place-6',
    is_example: true,
    spot_id: 'spot-5',
    user_id: 'seed-attendee-f',
    maker_name: 'Bram',
    title: 'Tiles for a kiosk that closed',
    description:
      'The kiosk sold chips here for forty years. Nine painted tiles, one for each thing that was on the menu board when it shut.',
    materials: 'Glazed ceramic, fixed to a board',
    image_url: img('course-ceramics'),
    placed_at: daysAgo(1),
    collect_by: inDays(13),
    status: 'live',
    collected_at: null,
  },
  /*
   * One piece is hidden rather than shown, so the hunt is visible on a first
   * visit. Without a seeded example the gallery's Hidden filter is empty and
   * the whole mechanic reads as something that was described but not built.
   */
  {
    id: 'place-7',
    is_example: true,
    spot_id: 'spot-7',
    user_id: 'seed-attendee-g',
    maker_name: 'Fenna',
    title: 'A very small library',
    description:
      'Eleven hand-stitched zines, each one four pages, in a tin. Take one if you find it — that is the point of them.',
    materials: 'Riso-printed paper, thread, biscuit tin',
    image_url: img('course-zine'),
    hunt_clue: 'Not on the gatepost — under it. Crouch at the Ringbaan side and feel along the ledge.',
    placed_at: daysAgo(4),
    collect_by: inDays(10),
    status: 'live',
    collected_at: null,
  },
  {
    id: 'place-4',
    is_example: true,
    spot_id: 'spot-6',
    user_id: 'seed-attendee-d',
    maker_name: 'Joost',
    title: 'Koningsplein, 03:00',
    description: 'A concrete cast of the square at its emptiest. Taken home on time.',
    materials: 'Cast concrete, steel pin',
    image_url: img('twoweeks-concrete'),
    placed_at: daysAgo(24),
    collect_by: daysAgo(10),
    status: 'collected',
    collected_at: daysAgo(11),
  },
];

export const seedCourses: Course[] = [
  {
    id: 'course-screenprint',
    is_example: true,
    title: 'Screenprinting: from sketch to edition',
    provider: 'Veemarkt Studios',
    description:
      'Four evenings from a drawing to a numbered run of fifteen prints. You learn stencils, registration and how to rescue a screen you have ruined, which you will. Everything you print is yours.',
    certificate: 'Studio certificate — screenprinting, level 1',
    format: 'certificate',
    discipline: 'Printmaking',
    level: 'beginner',
    points_cost: 100,
    cash_cost_euros: 180,
    sessions: 4,
    hours_total: 12,
    starts_on: daysFromNow(14, 19),
    location: { latitude: 51.559, longitude: 5.0895 },
    address: 'Veemarktstraat 62',
    image_url: img('course-screenprint'),
    accessibility: ['wheelchair', 'step_free'],
    capacity: 12,
    materials_included: true,
    created_at: daysAgo(30),
  },
  {
    id: 'course-darkroom',
    is_example: true,
    title: 'Analogue darkroom, start to finish',
    provider: 'Fontys Academy for Creative Industries',
    description:
      'Load a film in a changing bag, develop it, and print it by hand. Six sessions in a real darkroom with a tutor who will not let you skip the boring parts, because the boring parts are the craft.',
    certificate: 'Fontys short-course statement of participation',
    format: 'certificate',
    discipline: 'Photography',
    level: 'beginner',
    points_cost: 130,
    cash_cost_euros: 295,
    sessions: 6,
    hours_total: 18,
    starts_on: daysFromNow(21, 18, 30),
    location: { latitude: 51.5606, longitude: 5.0836 },
    address: 'Fontys, Spoorzone',
    image_url: img('course-darkroom'),
    accessibility: ['wheelchair', 'step_free', 'quiet'],
    capacity: 10,
    materials_included: true,
    created_at: daysAgo(28),
  },
  {
    id: 'course-sound-design',
    is_example: true,
    title: 'Sound design for film and games',
    provider: 'Fontys × 013',
    description:
      'Eight weeks building a sound library from the city itself and cutting it to picture. Ends with your work played through the 013 main room rig, which is not a thing you get to do twice.',
    certificate: 'Micro-credential — 3 ECTS, Fontys',
    format: 'certificate',
    discipline: 'Sound',
    level: 'some_experience',
    points_cost: 200,
    cash_cost_euros: 450,
    sessions: 8,
    hours_total: 32,
    starts_on: daysFromNow(28, 19),
    location: { latitude: 51.5573, longitude: 5.0842 },
    address: '013 Poppodium, Veemarktstraat 44',
    image_url: img('course-sound'),
    accessibility: ['wheelchair', 'step_free', 'hearing_loop'],
    capacity: 14,
    materials_included: false,
    created_at: daysAgo(26),
  },
  {
    id: 'course-natural-dye',
    is_example: true,
    title: 'Dyeing with what grows here',
    provider: 'TextielLab',
    description:
      'Three afternoons making colour out of onion skin, madder, oak gall and woad — the same chemistry that built this city, minus the part with the jugs. Bring a white cotton thing you are prepared to lose.',
    certificate: null,
    format: 'class',
    discipline: 'Textiles',
    level: 'any',
    points_cost: 60,
    cash_cost_euros: 95,
    sessions: 3,
    hours_total: 9,
    starts_on: daysFromNow(10, 14),
    location: { latitude: 51.5686, longitude: 5.0762 },
    address: 'TextielLab, Goirkestraat 96',
    image_url: img('course-dye'),
    accessibility: ['wheelchair', 'step_free', 'service_animal'],
    capacity: 16,
    materials_included: true,
    created_at: daysAgo(24),
  },
  {
    id: 'course-mural',
    is_example: true,
    title: 'Painting at wall scale',
    provider: 'Hall of Fame collective',
    description:
      'Five sessions on the legal wall learning what changes when a drawing becomes four metres tall — grids, perspective from below, and working fast before the light goes. You finish with a panel of your own.',
    certificate: 'Collective letter of completion',
    format: 'class',
    discipline: 'Mural & street art',
    level: 'some_experience',
    points_cost: 90,
    cash_cost_euros: 160,
    sessions: 5,
    hours_total: 20,
    starts_on: daysFromNow(18, 13),
    location: { latitude: 51.571, longitude: 5.068 },
    address: 'Hall of Fame, Quirijnstokstraat',
    image_url: img('course-mural'),
    accessibility: ['parking'],
    capacity: 10,
    materials_included: true,
    created_at: daysAgo(20),
  },
  {
    id: 'course-zine',
    is_example: true,
    title: 'Zines and very small publishing',
    provider: 'LocHal Kennismakerij',
    description:
      'Two sessions: make one, then work out how to get forty copies into the hands of people who are not your friends. Covers layout, risograph basics, distribution and pricing at zero.',
    certificate: null,
    format: 'class',
    discipline: 'Publishing',
    level: 'any',
    points_cost: 30,
    cash_cost_euros: 45,
    sessions: 2,
    hours_total: 6,
    starts_on: daysFromNow(9, 19),
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'LocHal, Kennismakerij',
    image_url: img('course-zine'),
    accessibility: ['wheelchair', 'quiet', 'step_free', 'hearing_loop'],
    capacity: 20,
    materials_included: true,
    created_at: daysAgo(18),
  },
  {
    id: 'course-ceramics',
    is_example: true,
    title: 'Hand-built ceramics',
    provider: 'Veemarkt Studios',
    description:
      'Six weeks of pinch, coil and slab, glazing in week five and firing in week six. No wheel, which is the honest way to start. Expect to break at least one thing you liked.',
    certificate: 'Studio certificate — ceramics, level 1',
    format: 'certificate',
    discipline: 'Ceramics',
    level: 'beginner',
    points_cost: 120,
    cash_cost_euros: 225,
    sessions: 6,
    hours_total: 18,
    starts_on: daysFromNow(24, 19),
    location: { latitude: 51.559, longitude: 5.0895 },
    address: 'Veemarktstraat 62',
    image_url: img('course-ceramics'),
    accessibility: ['wheelchair', 'step_free'],
    capacity: 12,
    materials_included: true,
    created_at: daysAgo(16),
  },
  {
    id: 'course-documentary',
    is_example: true,
    title: 'Documenting the street you live on',
    provider: 'Fontys Academy for Creative Industries',
    description:
      'Eight weeks photographing one street — yours — with weekly crits. Ends in a group show at the LocHal. The tutors are blunt and the work gets much better for it.',
    certificate: 'Micro-credential — 3 ECTS, Fontys',
    format: 'certificate',
    discipline: 'Photography',
    level: 'some_experience',
    points_cost: 190,
    cash_cost_euros: 450,
    sessions: 8,
    hours_total: 28,
    starts_on: daysFromNow(30, 18),
    location: { latitude: 51.5606, longitude: 5.0836 },
    address: 'Fontys, Spoorzone',
    image_url: img('course-documentary'),
    accessibility: ['wheelchair', 'step_free', 'hearing_loop'],
    capacity: 12,
    materials_included: false,
    created_at: daysAgo(14),
  },
  {
    id: 'course-lighting',
    is_example: true,
    title: 'Stage lighting: the first desk',
    provider: '013 Poppodium',
    description:
      'Four evenings on a real desk in a real room. Rigging, focusing, colour, and running a set for a live band on the last night. Counts towards a crew placement if you want one.',
    certificate: 'Venue crew certificate — lighting, entry level',
    format: 'certificate',
    discipline: 'Technical theatre',
    level: 'beginner',
    points_cost: 110,
    cash_cost_euros: 240,
    sessions: 4,
    hours_total: 16,
    starts_on: daysFromNow(16, 19),
    location: { latitude: 51.5573, longitude: 5.0842 },
    address: '013 Poppodium',
    image_url: img('course-lighting'),
    accessibility: ['wheelchair', 'step_free', 'hearing_loop'],
    capacity: 8,
    materials_included: true,
    created_at: daysAgo(12),
  },
  {
    id: 'course-writing',
    is_example: true,
    title: 'Writing in a language that is not your first',
    provider: 'LocHal × Buurthuis De Symfonie',
    description:
      'Six weeks for people writing in Dutch or English as a second, third or fourth language. Nobody corrects your grammar unless you ask. The accent is the point, not the problem.',
    certificate: 'Statement of participation',
    format: 'class',
    discipline: 'Writing',
    level: 'any',
    points_cost: 40,
    cash_cost_euros: 120,
    sessions: 6,
    hours_total: 12,
    starts_on: daysFromNow(12, 19),
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'LocHal, reading room',
    image_url: img('course-writing'),
    accessibility: ['wheelchair', 'quiet', 'step_free', 'hearing_loop', 'service_animal'],
    capacity: 15,
    materials_included: true,
    created_at: daysAgo(10),
  },
  {
    id: 'course-masterclass',
    is_example: true,
    title: 'Masterclass: Sanne de Wit on painting big in public',
    provider: 'Inclusivity Department',
    description:
      'One evening with the artist behind The Loom Wall on getting permission, getting paid, and getting a wall in the first place. Small group, questions encouraged, no portfolio required.',
    certificate: null,
    format: 'masterclass',
    discipline: 'Mural & street art',
    level: 'any',
    points_cost: 20,
    cash_cost_euros: 35,
    sessions: 1,
    hours_total: 3,
    starts_on: daysFromNow(8, 19, 30),
    location: { latitude: 51.5609, longitude: 5.0797 },
    address: 'LocHal, Stadszaal',
    image_url: img('course-masterclass'),
    accessibility: ['wheelchair', 'quiet', 'step_free', 'hearing_loop'],
    capacity: 30,
    materials_included: true,
    created_at: daysAgo(6),
  },
];

/** Enough feedback that safety scores clear the "3 reports" threshold. */
export const seedFeedback: Feedback[] = [
  ...buildFeedback('inst-lochal-loom', [5, 5, 4, 5], [5, 4, 5]),
  ...buildFeedback('inst-piushaven-lights', [4, 5, 4], [4, 4, 3]),
  ...buildFeedback('inst-dwaalgebied-mural', [4, 3, 4, 4], [3, 3, 2]),
  ...buildFeedback('inst-hall-of-fame', [3, 2, 3], [2, 2, 1]),
  ...buildFeedback('inst-leijpark-sound', [4, 4, 5], [2, 3, 2]),
  ...buildFeedback('inst-station-ceiling', [4, 4, 3, 4], [3, 4, 3]),
  ...buildFeedback('ts-lochal', [5, 5, 5, 4], [5, 5, 4]),
  ...buildFeedback('ts-wilhelminapark', [5, 4, 4], [3, 3, 4]),
  ...buildFeedback('ts-piushaven-kiosk', [4, 5, 4], [4, 4, 5]),
  ...buildFeedback('ts-hall-of-fame-cafe', [5, 4, 5], [4, 3, 4]),
  ...buildFeedback('ts-buurthuis-reeshof', [5, 5, 4], [4, 4, 5]),
  ...buildFeedback('route-lit-way-home', [5, 5, 4, 5], [5, 4, 5, 5]),
  ...buildFeedback('route-north-discovery', [4, 3, 4], [2, 3, 2]),
  ...buildFeedback('route-quiet-green', [5, 5, 4], [4, 4, 5]),
];

function buildFeedback(
  locationId: string,
  dayScores: number[],
  nightScores: number[],
): Feedback[] {
  const rows: Feedback[] = [];
  dayScores.forEach((score, i) => {
    rows.push({
      id: `fb-${locationId}-d${i}`,
      user_id: null,
      kind: 'safety',
      location_id: locationId,
      time_of_day: i % 2 === 0 ? 'afternoon' : 'morning',
      safety_perception: score,
      comment: null,
      is_anonymous: true,
      created_at: daysAgo(10 + i * 3),
    });
  });
  nightScores.forEach((score, i) => {
    rows.push({
      id: `fb-${locationId}-n${i}`,
      user_id: null,
      kind: 'safety',
      location_id: locationId,
      time_of_day: 'night',
      safety_perception: score,
      comment: null,
      is_anonymous: true,
      created_at: daysAgo(5 + i * 4),
    });
  });
  return rows;
}
